name: DrugMeUp
main: me.hammale.drugs.drugs
version: 1.0
author: hammale, gaz492, Giinger
commands:
  drugmeup:
    description:
    usage: "Incorrect usage. '/drugmeup reload'"
permissions:
    drugs.*:
        description: Gives access to all DrugMeUp features
        children:
            drugs.use: true
    drugs.use:
        description: Allows users to do drugs
        default: op    
    drugs.reload:
        description: Reloads the config
        default: op    